import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getFeaturedEvents } from "../dummy-data";
import EventList from "../components/events/event-list";

export default function Home() {

    const featuredEvents = getFeaturedEvents();


  return (
    <div className={styles.container}>
      <Head>
        <title>link practice home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <main className={styles.main}>
            <h1>home page</h1>

            <EventList items={featuredEvents}/>




        </main>



      <footer className={styles.footer}>

        <h4>the footer</h4>
      </footer>
    </div>
  )
}
